name: Build Article

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Podman
        run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get -y install podman

      - name: Install Make
        run: sudo apt-get -y install make

      - name: Install Datalad
        uses: datalad/datalad-action/install@main

      - name: Get data from datalad
        run: |
          git fetch gin.g-node.org
          datalad get outputs/*/article.pdf

      - name: Build container article
        working-directory: paper/source
        run: make container-article

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: paper-pdf
          path: paper/source/article.pdf
