name: Build Article

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Podman
        run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get -y install podman

      - name: Install Make
        run: sudo apt-get -y install make

      - name: Build container article
        run: make container-article

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: article-pdf
          path: article/article.pdf
